name: app
channels:
  - conda-forge
dependencies:
  - python=3.12
  - geopandas>=0.14
  - shapely>=2
  - pyproj
  - fiona
  - gdal
  - rtree            
  - pyogrio          
  - pip
  - pip:
      - shiny>=1.0.0
      - shinywidgets
      - plotly
      - folium
      - branca